CREATE TABLE "user"
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    verified     BOOLEAN                                 NOT NULL,
    passwordHash BYTEA                                   NOT NULL,
    mfa          BOOLEAN                                 NOT NULL,
    active       BOOLEAN                                 NOT NULL,
    createdAt    TIMESTAMP WITHOUT TIME ZONE,
    updatedAt    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);